# Numpy

In [1]:
import numpy as np 

**Matrices o Vectore**  
Al crear arrays con numpy arramos mucha memory ademas de que a difenrecia de python normal se tratan los array como vetores

In [2]:
A = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

B = np.array([
    [10,9,8,7,6],
    [5,4,3,2,1]
])

**Shape**  
Devuelve las diemnciones del arreglo 

In [3]:
A.shape 

(2, 5)

**Flatten**
Devuelve cualquier vector o matrix en una sola dimencion 

In [4]:
A.flatten() 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Reshape**  
Devuelve el vector o matrix cambiando sus dimenciones, mientras alla sucientes numeros  
Si usamos el argumento -1 hacemos que los otros argumentos se cumplam y que ese calculodo para lograrlo  

In [5]:
A.reshape(-1,2) 

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

**Arange**  
Devulve un array con el conjunto de numero desde el primreo hasta el ultimo 

In [6]:
C = np.arange(0,1000) 

**Zeros**  
Nos devuelve un vector de puros ceros segun las dimenciones que le pasemos   
Tambien existe una funcion zeros_like que nos devuelve un vector con las mismas dimenciones de otro vector que le pasemos, pero lleno de puros ceros

In [7]:
np.zeros([10,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

**Ones**  
Hace los mismo que zeros pero con unos, igualmente existe la funcion ones_like

In [8]:
np.ones([10,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

**Operaciones Matematicas**  
En numpy podemos aplicar casi cualquier operacion matematica a un vector con de esta manera 

In [9]:
np.sqrt(A)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766]])

**Where**  
Pasamos como argumento una pregunta aplicaada sobre un vector y nos devuelce los index donde se cumple esto 

In [10]:
A = np.array(
    [1,2,3,4,5]
)

D = np.where(A<2)
D

(array([0], dtype=int64),)